# Generated by Django 6.0.6 on 2026-07-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proucts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='phones/'),
        ),
    ]
