# Generated by Django 6.0.6 on 2026-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proucts', '0002_phone_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='stock',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
