# Generated by Django 6.0.6 on 2026-07-10 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proucts', '0006_favoerite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favoerite',
            new_name='Favorite',
        ),
    ]
